### ISSUE TITLE
problem handling failed jobs

### ISSUE THREAD

**Issue by hmenager** [common-workflow-lab/galaxy#110]
When testing that a job fails, I saw that as the job failed, the job handler seemed to enter a loop due to a bug in the "failure handling":
```python
galaxy.jobs.runners.local WARNING 2019-07-06 07:27:19,443 [p:267,w:1,m:0] [LocalRunner.work_thread-3] stop_job(): 36: no PID in database for job, unable to stop
galaxy.jobs.runners ERROR 2019-07-06 07:27:19,520 [p:267,w:1,m:0] [LocalRunner.work_thread-3] (unknown) Unhandled exception calling fail_job
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 131, in run_next
    method(arg)
  File "lib/galaxy/jobs/runners/__init__.py", line 454, in fail_job
    job_state.job_wrapper.fail(getattr(job_state, 'fail_message', 'Job failed'), exception=exception)
  File "lib/galaxy/jobs/__init__.py", line 1225, in fail
    context_ext = context.get('ext', 'data')
NameError: global name 'context' is not defined
```
And indeed, it seems `context` is not defined there:
https://github.com/common-workflow-language/galaxy/blob/cwl-1.0/lib/galaxy/jobs/__init__.py#L1225

**Comment by hmenager** [comment]
this code
```python
context_ext = context.get('ext', 'data')
if dataset.ext == 'auto' or dataset.ext == 'data' and context_ext != 'data':
    dataset.extension = context_ext
```

is not in main (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/__init__.py#L1220)
nor in prerebase of cwlgalaxy fork (https://github.com/common-workflow-language/galaxy/blob/cwl-1.0/lib/galaxy/jobs/__init__.py#L1225)

```python
if dataset.ext == 'auto':
    dataset.extension = 'data'
