### ISSUE TITLE
problem with workflows upload

### ISSUE THREAD

**Issue by hmenager** [common-workflow-lab/galaxy#111]
Workflow upload seems to generate some server side problems:
```python
galaxy.web.framework.decorators ERROR 2019-07-06 08:09:45,601 [p:293,w:1,m:0] [uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/workflows.py", line 499, in import_new_workflow_deprecated
    return self.__api_import_new_workflow(trans, payload, **kwd)
  File "lib/galaxy/webapps/galaxy/api/workflows.py", line 632, in __api_import_new_workflow
    raw_workflow_description = self.__normalize_workflow(trans, data)
  File "lib/galaxy/webapps/galaxy/api/workflows.py", line 702, in __normalize_workflow
    return self.workflow_contents_manager.normalize_workflow_format(trans, as_dict)
  File "lib/galaxy/managers/workflows.py", line 308, in normalize_workflow_format
    from galaxy.tools.cwl import workflow_proxy
ImportError: No module named cwl
```
Will check on that to update #109 if appropriate

**Comment by hmenager** [comment]
this one is probably bogus, sorry!
